# Generated by Django 3.1 on 2020-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_img', models.ImageField(default='C:\\Users\\shamil\\Desktop\\SAML\\SentimentAnalysis\\static/avengers2.jpg', upload_to='static/')),
                ('movie_title', models.CharField(max_length=100)),
                ('storyline', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('impression', models.CharField(max_length=100)),
            ],
        ),
    ]
