# Generated by Django 3.1 on 2020-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
