# Generated by Django 3.1 on 2020-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAA', '0002_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
